-- ==========================================================
-- MODULE 1 : KPI ANALYSIS
-- ==========================================================

/*=======================================
Query 1 : total revenue 
purpose : calculate total revenue generated from all orders.
=========================================*/

select sum(totalamount) as total_revenue from orderdetails;

/* =====================
Query 2 : total orders
purpose : count total numbers of orders
========================*/

select count(*) as total_orders from orders;

/*===============
query 3 : totoal customers 
purpose : count total customers
================*/

select count(*) as total_customers from customers;

/*==============
query 4 : total products
purpose : count total products
*/

select count(*) as total_products from products;

/*=================
query 5 : total sellers
purpose : count total sellers
*/

select count(*) as total_sellers from sellers;

/*================
query 6 : total quantity sold
purpose : calculate total quantity sold
*/

select sum(quantity) as total_quantity_sold from orderdetails;

/* ============
query 7 : average ordervalue 
purpose : calculate average value per order
*/

select round(avg(totalamount),2) as average_ordervalue from orderdetails;


/*============================================================
 MODULE 2 : PRODUCT ANALYSIS
 Purpose : Analyze product performance, revenue, and sales.
============================================================*/

/*===========
query 8 : top 10 product by revenue 
purpose : identify the top 10 revenue generated by products
*/

select productname , sum(totalamount) as total_revenue from orderdetails
inner join products using(productkey) 
group by 1
order by total_revenue desc
limit 10;

/*=============
query 9 : bottom 10 product by revenue 
purpose : identify the lowest generated by products
*/

select productname , sum(totalamount) as total_revenue from orderdetails 
inner join products using(productkey) 
group by 1
order by total_revenue asc
limit 10;

/*=============
query 10 : top 10 categories by revenue
purpose : identify the highest revenue generated by categories
*/


select category , sum(totalamount) as total_revenue from orderdetails 
inner join products using(productkey) 
group by 1
order by total_revenue desc;

/*============
query 11 : top brands by revenue 
purpose : identify highet revenue-generating brands 
*/

-- 12 product wise average discount
select productname , round(avg(discount),2) as average_discount from orderdetails
inner join products using(productkey) 
group by 1 
order by average_discount desc;

select brand , sum(totalamount) as total_revenue from orderdetails inner join products
using(productkey) group by 1
order by total_revenue desc;

-- 13 numers of orders per products 

select productname , count(distinct orderid) as total_orders from orderdetails 
inner join products using(productkey) group by 1
order by total_orders desc;

/*============================================================
 Query 14 : Average Selling Price
 Purpose : Calculate average selling price of each product.
============================================================*/

select productname , round(avg(unitprice),2) as average_selling_price from orderdetails
inner join products using(productkey) 
group by 1
order by average_selling_price desc;

/*============================================================
 Query 15 : Most Sold Product
 Purpose : Identify the product with the highest quantity sold.
============================================================*/

select productname ,sum(quantity) as total_quantity_sold from orderdetails 
inner join products using(productkey) 
group by 1
order by total_quantity_sold desc limit 1;

/*============================================================
 Query 16 : Least Sold Product
 Purpose : Identify the product with the lowest quantity sold.
============================================================*/

select productname , sum(quantity) as total_quantity_sold from orderdetails 
inner join products using(productkey) 
group by 1
order by total_quantity_sold asc limit 1;

/*============================================================
 Query 17 : Product-wise Quantity Sold
 Purpose : Calculate quantity sold for each product.
============================================================*/

select productname , sum(quantity) as total_quantity_sold  from orderdetails 
inner join products  using(productkey) 
group by 1
order by total_quantity_sold desc;


-- ============================================================
-- MODULE 3 : CUSTOMER ANALYSIS
-- Purpose : Analyze customer purchasing behavior and revenue contribution.
-- ============================================================

/*============================================================
 Query 18 : Top 10 Customers by Revenue
============================================================*/

select customername, sum(totalamount) as total_revenue from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)  
group by 1 
order by total_revenue desc  limit 10 ;

/*============================================================
 Query 19 : Bottom 10 Customers by Revenue
============================================================*/

select customername ,sum(totalamount) as total_revenue from customers 
inner join orders using(customerkey) 
inner join orderdetails using(orderid) 
group by 1 order by total_revenue asc  limit 10;

/*============================================================
 Query 20 : Customer-wise Total Orders
============================================================*/

select customername , count(orderid) as total_orders from customers 
inner join orders using(customerkey) 
inner join orderdetails using(orderid) 
group by 1
order by total_orders desc limit 10;

/*============================================================
 Query 21 : Average Order Value per Customer
============================================================*/

select customername , ROUND(avg(totalamount),2) as avg_ordervalue from customers 
inner join orders using(customerkey)
inner join orderdetails using(orderid)
group by 1 order by avg_ordervalue desc;

/*============================================================
 Query 22 : Customer-wise Total Quantity Purchased
============================================================*/

select customername , sum(quantity) as total_quantity_orders from customers 
inner join orders using(customerkey) 
inner join orderdetails using(orderid)
group by 1
order by total_quantity_orders desc;

/*============================================================
 Query 23 : Top Cities by Revenue
============================================================*/

select city , sum(totalamount) as total_revenue from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by total_revenue desc;

/*============================================================
 Query 24 : Top States by Revenue
============================================================*/

select state , sum(totalamount) as total_revenue from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by total_revenue desc;

/*============================================================
 Query 25 : Top Countries by Revenue
============================================================*/

select country , sum(totalamount) as total_revenue from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid) 
group by 1 order by total_revenue desc;

/*============================================================
 Query 26 : Customer Lifetime Value (CLV)
============================================================*/

select customername , sum(totalamount) as customer_lifetime from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by customer_lifetime desc;

/*============================================================
 Query 27 : Repeat Customers
============================================================*/

select customername , count(orderid) as total_orders from customers 
inner join orders using(customerkey) 
group by 1 having count(orderid) > 1 
order by total_orders desc ;


/*============================================================
 MODULE 4 : SALES ANALYSIS
 Purpose : Analyze sales performance across different dimensions.
============================================================*/

/*============================================================
 Query 28 : Monthly Revenue
============================================================*/

select monthname(orderdate) as months , sum(totalamount) as total_revenue from orders 
inner join orderdetails using(orderid) 
group by month(orderdate) , monthname(orderdate)
order by month(orderdate) asc;

/*============================================================
 Query 29 : Monthly Order Count
============================================================*/

select monthname(orderdate) as months , count(orderid) as total_orders from orders 
group by 1 order by total_orders desc;

/*============================================================
 Query 30 : Revenue by Order Status
============================================================*/

select orderstatus , sum(totalamount) as total_revenue from orders 
inner join orderdetails using(orderid) 
group by 1  order by total_revenue desc;

/*============================================================
 Query 31 : Revenue by Payment Method
============================================================*/

select paymentmethod , sum(totalamount) as total_revenue from orders 
inner join orderdetails using(orderid) 
group by 1 order by total_revenue desc;

/*============================================================
 Query 32 : Average Revenue per Month
============================================================*/

select monthname(orderdate) as months , round(avg(totalamount),2) as avg_revenue 
from orders inner join orderdetails using(orderid) 
group by 1 order by avg_revenue desc;

/*============================================================
 Query 33 : Highest Sales Month
============================================================*/

select monthname(orderdate) as months , sum(totalamount) as total_revenue from orders 
inner join orderdetails using(orderid)
group by 1 order by total_revenue desc limit 1;  

/*============================================================
 Query 34 : Lowest Sales Month
============================================================*/

select monthname(orderdate) as months , sum(totalamount) as total_revenue from orders 
inner join orderdetails using(orderid) 
group by 1 order by total_revenue asc limit 1; 

/*============================================================
 Query 35 : Monthly Quantity Sold
============================================================*/

select monthname(orderdate) as months , sum(quantity) as total_quantity_sold from orders
inner join orderdetails using(orderid) 
group by 1 order by  monthname(orderdate) asc   ;

/*============================================================
 MODULE 5 : LOCATION ANALYSIS
 Purpose : Analyze sales performance based on location.
============================================================*/

/*============================================================
 Query 36 : City-wise Total Orders
============================================================*/

select city , count(orderid) as total_orders from orders inner join customers
using(customerkey) group by 1 order by total_orders desc ;

/*============================================================
 Query 37 : State-wise Total Orders
============================================================*/

select state, count(orderid) as total_orders from orders 
inner join customers using(customerkey) 
group by 1 order by total_orders desc;

select country , count(orderid) as total_orders from orders 
inner join customers using(customerkey) 
group by 1 order by total_orders desc;

/*============================================================
 Query 39 : City-wise Quantity Sold
============================================================*/

select city , sum(quantity) as quantity_sold from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by quantity_sold desc;

/*============================================================
 Query 40 : State-wise Quantity Sold
============================================================*/

select state , sum(quantity) as total_quantity_sold from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by total_quantity_sold desc ;

/*============================================================
 Query 41 : Country-wise Quantity Sold
============================================================*/

select country , sum(quantity) as total_quantity_sold from customers 
inner join orders using(customerkey)  inner join orderdetails using(orderid)
group by 1 order by total_quantity_sold desc;

/*============================================================
 Query 42 : Top 10 Cities by Quantity Sold
============================================================*/

select city , sum(quantity) as total_quantity_sold from customers 
inner join orders using(customerkey) inner join orderdetails using(orderid)
group by 1 order by total_quantity_sold desc limit 10 ;




 





 












