/*============================================================
 Author  : Samshad Ansari
 Project : Amazon Sales Data Warehouse
 File    : 11_create_stored_procedures.sql
 Purpose : Create Stored Procedures for Business Reports
============================================================*/

/*============================================================
 Procedure 1 : Get Customer Revenue Report
 Purpose     : Display total revenue generated by each customer.
============================================================*/

delimiter $$ 
create procedure GetCustomerRevenue()
begin 
	select customername  , round(sum(totalamount),2) as total_revenue from customers 
    inner join orders using(customerkey) 
    inner join orderdetails using(orderid) 
    group by 1 
    order by total_revenue desc ;
    
end $$
delimiter ;

call GetCustomerRevenue();

/*============================================================
 Procedure 2 : Get Top 10 Customers
 Purpose     : Display top 10 customers by revenue.
============================================================*/ 

delimiter $$ 
create procedure GetTopCustomers(in top_n int)
begin 
	select customername , round(sum(totalamount),2) as total_revenue
    from customers inner join orders using(customerkey) 
    inner join orderdetails using(orderid)
    group by 1 
    order by total_revenue desc limit top_n;
    
end $$ 
delimiter ;

call GetTopCustomers(15);


-- ============================================================
-- MODULE 2 : PRODUCT PROCEDURES
-- ============================================================

/*============================================================
 Procedure 3 : Get Product Revenue Report
 Purpose     : Display revenue generated by each product.
============================================================*/

delimiter $$ 
create procedure GetProductRevenue()
begin 
	select productname , round(sum(totalamount),2) as total_revenue
    from products inner join orderdetails using(productkey) 
    group by 1 
    order by total_revenue desc ;
end $$ 
delimiter ;

call GetProductRevenue();

/*============================================================
 Procedure 4 : Get Top 10 Products
 Purpose     : Display top 10 revenue-generating products.
============================================================*/
delimiter $$ 
create procedure GetTopProduct(in top_n int)
begin 
	select productname , round(sum(totalamount),2) as total_revenue
    from products inner join orderdetails using(productkey) 
    group by 1 
    order by total_revenue desc limit top_n ;
end $$ 
delimiter ;

call GetTopProduct(11)

-- ============================================================
-- MODULE 3 : SALES PROCEDURES
-- ============================================================

/*============================================================
 Procedure 5 : Monthly Revenue Report
 Purpose     : Display monthly revenue summary.
============================================================*/

delimiter $$ 
create procedure monthly_revenue()
begin 
	select monthname(orderdate) as months , round(sum(totalamount),2) as total_revenue
    from orders inner join orderdetails using(orderid) 
    group by 1 
    order by total_revenue desc ;
    
end $$ 
delimiter ;

call monthly_revenue();

/*============================================================
 Procedure 6 : Category Revenue Report
 Purpose     : Display category-wise revenue.
============================================================*/

delimiter $$ 
create procedure Category_revenue()
begin 
	select category , round(sum(totalamount),2) as total_revenue 
    from products inner join orderdetails using(productkey) 
    group by 1 
    order by total_revenue desc ;
    
end $$ 
delimiter ;

call Category_revenue;

/*============================================================
 Procedure 7 : Brand Revenue Report
 Purpose     : Display brand-wise revenue.
============================================================*/

delimiter $$ 
create procedure Brand_revenue()
begin 
	select brand , round(sum(totalamount),2) as total_revenue from products 
    inner join orderdetails using(productkey) 
    group by 1 
    order by total_revenue desc ;
    
end $$ 
delimiter ;

call Brand_revenue();

/*============================================================
 Procedure 8 : Revenue by State
 Purpose     : Display state-wise revenue.
============================================================*/

delimiter $$ 
create procedure state_revenue()
begin 
	select state , round(sum(totalamount),2) as total_revenue from customers 
    inner join orders using(customerkey) 
    inner join orderdetails using(orderid)
    group by 1 
    order by total_revenue desc ;
    
end $$ 
delimiter ;

call state_revenue();







